
# ETCD instance
etcd:
    image: microbox/etcd:latest
    command: -name etcd
    ports:
        - 4001:4001
        - 7001:7001
    volumes:
        - /var/etcd/:/data

# Container registering in ETCD
register:
    build: ./register
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    environment:
        - HOST_IP=$HOST_IP
        - ETCD_HOST=$ETCD_HOST

# HaProxy Container with discovery
discovery:
    build: ./discovery
    net: host
    ports:
        - 127.0.0.1:1936:1936
    environment:
        - ETCD_HOST=$ETCD_HOST
    volumes:
        - /var/log

# Docker REST API
api:
    build: ./api
    ports:
        - 32854:12053
    environment:
        - NIXUS_12053=dockerapi
    privileged: true
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

# Monitor
cadvisor:
    image: google/cadvisor:latest
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
    ports:
        - 32888:8080
    environment:
        - NIXUS_8080=cadvisor
    command: -storage_driver="elasticsearch" -alsologtostderr=true -storage_driver_es_host="http://elasticsearch:9200"
    links:
        - elasticsearch

# ELK STACK
elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
        - 9200:9200
        - 9300:9300
    volumes_from:
        - elastic_data

elastic_data:
    image: busybox
    volumes:
        - /user/share/elasticsearch/data
        - /user/share/elasticsearch/plugins
        - /user/share/elasticsearch/config

logstash:
    image: logstash:latest
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
        - ./elk/logstash/config:/etc/logstash/conf.d
    ports:
        - 5000:5000
    links:
        - elasticsearch

kibana:
    build: elk/kibana/
    volumes:
        - ./elk/kibana/config/:/opt/kibana/config/
    ports:
        - 32889:5601
    links:
        - elasticsearch
    environment:
        - NIXUS_5601=kibana
