#! /bin/bash

RESTORE_PATH=$(pwd)

NIXUS_HOME=~/.nixus
cd $NIXUS_HOME

source ./env.sh

build() {
    docker-compose build
}

start() {
    case $1 in
        monitor)
            docker-compose up -d cadvisor elasticsearch elastic_data logstash kibana
            ;;
        all)
            docker-compose up -d
            ;;
        *)
            docker-compose up -d etcd register discovery api
            ;;
    esac
}

stop() {
    docker-compose down
}

uninstall() {
    stop
    rm /usr/local/bin/nixus
    echo "To clean completely: $ rm -rf $(pwd)"
}

logs() {
    docker-compose logs $1
}

# Get containers that have a proper NIXUS_<PORT>
ps() {
    docker inspect -f "{{.Id}} {{.Config.Env}}" $(docker ps -a | awk 'NR>1 {print $1}') | grep --color=always "NIXUS_[^ ]*"
}

# Open a terminal in an specific containers
ssh() {
    docker exec -it nixus_$1_1 bash
}

case "$1" in
        start)
            start $2
            ;;

        stop)
            stop
            ;;

        build)
            build
            ;;
        restart)
            stop
            start
            ;;
        uninstall)
            uninstall
            ;;
        ps)
            ps
            ;;
        ssh)
            ssh $2
            ;;
        logs)
            logs $2
            ;;
        *)
            echo $"Usage: $0 {start|stop|restart|build|uninstall|ps|ssh|logs}"
            exit 1

esac

cd $RESTORE_PATH
