#! /bin/bash

RESTORE_PATH=$(pwd)

NIXUS_HOME=~/.nixus
cd $NIXUS_HOME

source ./env.sh

build() {
    docker-compose build
}

start() {
    docker-compose up -d
} 

logs() {
    docker-compose logs
}

stop() {
    docker-compose stop
}

uninstall() {
    rm /usr/local/bin/nixus
    echo "To clean completely: $ rm -rf $(pwd)"
}


case "$1" in
        start)
            start
            ;;
         
        stop)
            stop
            ;;
         
        build)
            status build
            ;;
        restart)
            stop
            start
            ;;
         
        *)
            echo $"Usage: $0 {start|stop|restart|build}"
            exit 1
 
esac

cd RESTORE_PATH